name: Q3 Workflow

on:
  push:
    branches:
      - main

jobs:
  create-and-push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Q3.java
        run: |
          echo 'public class Q3 {' > Q3.java
          echo '    public static void main(String[] args) {' >> Q3.java
          echo '        if (args.length < 1) {' >> Q3.java
          echo '            System.out.println("Veuillez fournir un nombre en paramètre.");' >> Q3.java
          echo '            return;' >> Q3.java
          echo '        }' >> Q3.java
          echo '' >> Q3.java
          echo '        int n = Integer.parseInt(args[0]);' >> Q3.java
          echo '' >> Q3.java
          echo '        for (int i = 0; i < n; i++) {' >> Q3.java
          echo '            System.out.print("*");' >> Q3.java
          echo '        }' >> Q3.java
          echo '' >> Q3.java
          echo '        System.out.println();' >> Q3.java
          echo '    }' >> Q3.java
          echo '}' >> Q3.java

      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom : Deslandes" > Q3_archive_java.txt
          echo "Prénom : Killian" >> Q3_archive_java.txt
          echo "Email : killian.deslandes53@gmail.com" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu de Q3.java :" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit changes
        run: |
          git add Q3_archive_java.txt
          git commit -m "Add Q3_archive_java.txt with Q3.java and user details" || echo "No changes to commit"

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/KillianDlds/R5-07-DS.git
          git push
