name: Q4 Workflow

on:
  push:
    branches:
      - main

jobs:
  create-and-push-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Q4.java exists
        run: |
          if [ ! -f Q4.java ]; then
            echo "Le fichier Q4.java n'a pas été trouvé !"
            exit 1
          else
            echo "Le fichier Q4.java a été trouvé."
          fi

      - name: Create Q4_archive_date.txt
        run: |
          DATE=$(date +%d-%m-%Y)
          FILENAME="Q4_archive_${DATE}.txt"
          
          echo "Nom : Deslandes" > $FILENAME
          echo "Prénom : Killian" >> $FILENAME
          echo "" >> $FILENAME
          echo "Contenu de Q4.java :" >> $FILENAME
          
          cat Q4.java >> $FILENAME

      - name: List files after creation
        run: |
          echo "Fichier créé : $FILENAME"
          ls -l

      - name: Configure Git
        run: |
          git config --global user.name "KillianDlds"
          git config --global user.email "killian.deslandes53@gmail.com"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase

      - name: Add all files to Git
        run: |
          git add -A
          git status

      - name: Commit and push changes
        run: |
          git commit -m "Add $FILENAME with Q4.java content and user details" || echo "No changes to commit"
          git push
